import { cp, mkdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import type { ShotView } from "./frame.js";
import { OFFICIAL_MODS, RIG_MOD_TEMPLATE, TEMP_MOD_DIR_PREFIX } from "./paths.js";

export type CaptureJob = {
  name: string;
  blueprint: string;
  showEntityInfo?: boolean;
  /** Blueprint wires `[e1, c1, e2, c2][]` — reconnected after create_entity fallback. */
  wires?: [number, number, number, number][];
  /** When set, Factorio uses this fpsr-planned camera instead of entity bbox. */
  view?: ShotView;
  /** Fallback zoom when `view` is omitted. */
  zoom?: number;
};

export type StageJobsOptions = {
  /** Default zoom for jobs that omit view/zoom. */
  zoom?: number;
  /** Enabled game mods. Defaults to the existing all-official capture profile. */
  enabledMods?: readonly string[];
  jobs: CaptureJob[];
};

function luaStringLiteral(value: string): string {
  return JSON.stringify(value);
}

function renderJobLua(job: CaptureJob): string {
  const lines = [
    `      name = ${luaStringLiteral(job.name)},`,
    `      blueprint = ${luaStringLiteral(job.blueprint)},`,
    `      show_entity_info = ${job.showEntityInfo ? "true" : "false"},`,
  ];
  if (job.wires && job.wires.length > 0) {
    const wireRows = job.wires
      .map((w) => `        {${w[0]}, ${w[1]}, ${w[2]}, ${w[3]}}`)
      .join(",\n");
    lines.push(`      wires = {\n${wireRows}\n      },`);
  }
  if (job.view) {
    lines.push(`      zoom = ${job.view.zoom},`);
    lines.push(`      min_x = ${job.view.minX},`);
    lines.push(`      min_y = ${job.view.minY},`);
    lines.push(`      max_x = ${job.view.maxX},`);
    lines.push(`      max_y = ${job.view.maxY},`);
  } else if (job.zoom != null) {
    lines.push(`      zoom = ${job.zoom},`);
  }
  return `    {\n${lines.join("\n")}\n    }`;
}

export function renderJobsLua(opts: StageJobsOptions): string {
  const zoom = opts.zoom ?? 2;
  return `-- Generated by @fpsr/ground-truth — do not edit.
return {
  zoom = ${zoom},
  jobs = {
${opts.jobs.map(renderJobLua).join(",\n")}
  },
}
`;
}

export type StagedMods = {
  modDir: string;
  rigModDir: string;
  names: string[];
};

/** Stage a fresh temp mod directory with official mod-list + multi-job fpsr-rig. */
export async function stageJobs(opts: StageJobsOptions): Promise<StagedMods> {
  if (opts.jobs.length === 0) {
    throw new Error("stageJobs requires at least one job");
  }
  for (const job of opts.jobs) {
    if (!job.name.trim()) throw new Error("Capture job has empty name");
    if (!job.blueprint.trim()) throw new Error(`Capture job "${job.name}" has empty blueprint`);
  }
  const enabledMods = [...(opts.enabledMods ?? OFFICIAL_MODS)];
  if (!enabledMods.includes("base")) {
    throw new Error('stageJobs enabledMods must include "base" (fpsr-rig depends on it)');
  }
  if (new Set(enabledMods).size !== enabledMods.length) {
    throw new Error("stageJobs enabledMods contains duplicates");
  }

  const modDir = `${TEMP_MOD_DIR_PREFIX}-${process.pid}-${Date.now()}`;
  const rigModDir = path.join(modDir, "fpsr-rig");

  await mkdir(modDir, { recursive: true });
  await cp(RIG_MOD_TEMPLATE, rigModDir, { recursive: true });

  const scenarioDir = path.join(rigModDir, "scenarios", "rig");
  await writeFile(path.join(scenarioDir, "jobs.lua"), renderJobsLua(opts), "utf8");

  const modList = {
    mods: [
      ...OFFICIAL_MODS.map((name) => ({ name, enabled: enabledMods.includes(name) })),
      ...enabledMods
        .filter((name) => !(OFFICIAL_MODS as readonly string[]).includes(name))
        .map((name) => ({ name, enabled: true })),
      { name: "fpsr-rig", enabled: true },
    ],
  };
  await writeFile(
    path.join(modDir, "mod-list.json"),
    `${JSON.stringify(modList, null, 2)}\n`,
    "utf8",
  );

  return {
    modDir,
    rigModDir,
    names: opts.jobs.map((j) => j.name),
  };
}

export async function cleanupMods(modDir: string): Promise<void> {
  await rm(modDir, { recursive: true, force: true });
}
