import type { DistillDomainRoutes } from "./types.js";

/** Factorio Wiki Logistics: transport, storage, fluids, circuit, power, and robots. */
export const LOGISTICS_ROUTES = {
  container: "simple-picture",
  "proxy-container": "simple-picture",
  "linked-container": "simple-picture",
  "logistic-container": "logistic-container",
  "infinity-container": "logistic-container",
  inserter: "inserter",
  "electric-pole": "electric-pole",
  "pipe-to-ground": "pipe-to-ground",
  pipe: "pipe",
  "infinity-pipe": "infinity-pipe",
  "storage-tank": "storage-tank",
  pump: "pump",
  valve: "pump",
  "transport-belt": "belt",
  "underground-belt": "underground-belt",
  loader: "loader",
  "loader-1x1": "loader",
  "linked-belt": "linked-belt",
  splitter: "splitter",
  "lane-splitter": "splitter",
  "straight-rail": "rail-ground",
  "half-diagonal-rail": "rail-ground",
  "curved-rail-a": "rail-ground",
  "curved-rail-b": "rail-ground",
  "legacy-straight-rail": "rail-ground",
  "legacy-curved-rail": "rail-ground",
  "elevated-straight-rail": "rail-elevated",
  "elevated-half-diagonal-rail": "rail-elevated",
  "elevated-curved-rail-a": "rail-elevated",
  "elevated-curved-rail-b": "rail-elevated",
  "rail-ramp": "rail-ramp",
  "rail-support": "rail-support",
  "rail-signal": "rail-signal",
  "rail-chain-signal": "rail-signal",
  locomotive: "train",
  "cargo-wagon": "train",
  "fluid-wagon": "train",
  "infinity-cargo-wagon": "train",
  "arithmetic-combinator": "combinator",
  "decider-combinator": "combinator",
  "constant-combinator": "combinator",
  "selector-combinator": "combinator",
  "display-panel": "combinator",
  "power-switch": "power-switch",
  roboport: "roboport",
  "train-stop": "train-stop",
  lamp: "lamp",
  "programmable-speaker": "speaker",
  "construction-robot": "robot",
  "logistic-robot": "robot",
} as const satisfies DistillDomainRoutes;
